services:
  db:
    image: postgres:16.10-alpine
    container_name: social-db
    environment:
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_password
      POSTGRES_DB: social_db
    ports:
      - "5432:5432"
    volumes:
      - social-db-data:/var/lib/postgresql/data

volumes:
  social-db-data:
